### PR TITLE
Fix bad scale propagation to label

### PR DESCRIPTION
**Pull request by mosquitoe**

### CODE REVIEW

**Comment by johncbowman** [comment]
The suggested change would completely disable the embed argument, which determines how the Label should transform with the embedding picture. You can specify a custom embedding function when constructing a Label so it isn't necessary to disable it for everyone else.

If you post an example of what you are trying to accomplish, we should be able to help you.

**Comment by mosquitoe** [comment]
See this: 

```
picture pxc;
label(pxc, Label("G"), (0,0));
shipout("pxc", xscale(-1) * pxc);

picture pyc;
label(pyc, Label("G"), (0,0));
shipout("pyc", yscale(-1) * pyc);
```

The behavior of this is contra-intuitive. Why does the y-flip result to 180° rotation and x-flip to identity?

**Comment by johncbowman** [comment]
By default, Labels should only shift and rotate with the embedding picture. But as described in the documentation, you can force Labels to shift, rotate, slant, reflect, and scale with the embedding picture like this:

picture pxc;
label(pxc, Label("G",Scale), (0,0));
shipout("pxc", xscale(-1) * pxc);

picture pyc;
label(pyc, Label("G",Scale), (0,0));
shipout("pyc", yscale(-1) * pyc);

The reason for the unusual behaviour you noted was due an asymmetry in angle(transform t),
which is now fixed in c2ca99da1f5587e077cd0e7c367b49d5eae7a172.

**Comment by mosquitoe** [comment]
Thanks for your explanation!

**Pull request closed without merging**
