### PR TITLE
Fixing bugs in the inversion section of the `geometry` module

### PR DESCRIPTION
**Pull request by yarusome**
This PR fixes bugs related to coordinate systems in the inversion section of the `geometry` module, and simplifies the internal use of `inversion`.

### CODE REVIEW

**Comment by yarusome** [comment]
Btw, the `geometry` module contains a lot of `asyxml` tags, which form a large part of the source code and seem to be used for documentation. However, it's the only module that has such tags, so I guess these tags are no longer needed. If so, I'd create another PR to clean them up.

**Comment by ivankokan** [comment]
> Btw, the `geometry` module contains a lot of `asyxml` tags, which form a large part of the source code and seem to be used for documentation. However, it's the only module that has such tags, so I guess these tags are no longer needed. If so, I'd create another PR to clean them up.

Please do not. Check this, still on my TODO list...
- https://sourceforge.net/p/asymptote/discussion/409349/thread/f07c1fcf/
- https://github.com/vectorgraphics/asymptote/wiki

**Comment by yarusome** [comment]
@ivankokan I'll leave them there, then. But beware that there're various incorrect signatures and format inconsistency in these tags.

**Comment by johncbowman** [comment]
These errors need to be fixed:
```
asy
import geometry;

  point Ap = inverse(k, A, s.A), Bp = inverse(k, A, s.B),
                    ^
base/geometry.asy: 7157.21: no matching function 'inverse(real, point, point)'
  point Ap = inverse(k, A, s.A), Bp = inverse(k, A, s.B),
                                             ^
base/geometry.asy: 7157.46: no matching function 'inverse(real, point, point)'
    M = inverse(k, A, midpoint(s));
               ^
base/geometry.asy: 7158.16: no matching function 'inverse(real, point, point)'

```

**Comment by yarusome** [comment]
@johncbowman Fixed, and no other incorrect use of `inverse()` remains now.

**Comment by yarusome** [comment]
@johncbowman Would this PR be merged soon? It has been sitting here for months. If there're any pending problems in this PR, I could fix them as soon as possible.

**Pull request merged**
